[package]
name = "no-as-a-service-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["serde_derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.2", features = ["full"] }
